/*
 * This source file was generated by the Gradle 'init' task
 */
package asset_management;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;

import asset_management.views.HomeView;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {

        HomeView homeView = new HomeView();
        // System.out.println(new App().getGreeting());
        // Database db = new Database();
        // ResultSet result = db.queryAll("TestTable");
        // while (result.next()) {
        //     try {
        //         System.out.println(result.getString("firstName"));

        //     } catch (SQLException error) {
        //         System.out.println("SQLexception: " + error.getMessage());
        //         System.out.println("SQLState: " + error.getSQLState());
        //         System.out.println("VendorError: " + error.getErrorCode());System.out.println(error);
        //     }
        // }

        // HashMap<String, Object> values = new HashMap<>();
        // values.put("firstName", "Ricardo");
        // values.put("employeeID", 9999);
        // db.insertInto("TestTable", values);

        // db.createTable(null, null);

        // db.closeSQLObjects();
    }
}
